// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06RyvmpLi8YruM14woMgYU-5Hkj1VIdo',
    appId: '1:604492965652:web:7b838b6d6470f8f5350401',
    messagingSenderId: '604492965652',
    projectId: 'flutterexplore-cf65b',
    authDomain: 'flutterexplore-cf65b.firebaseapp.com',
    storageBucket: 'flutterexplore-cf65b.firebasestorage.app',
    measurementId: 'G-BWX52GVGLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDu4ih1lyN0GaLZeW7Q2aF33985VcN-T8',
    appId: '1:604492965652:android:f956a80d35a2eb7a350401',
    messagingSenderId: '604492965652',
    projectId: 'flutterexplore-cf65b',
    storageBucket: 'flutterexplore-cf65b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKW8a3lzfKN4YrsMfSk3ZByj7Wt-cdD0',
    appId: '1:604492965652:ios:425af3da97b24031350401',
    messagingSenderId: '604492965652',
    projectId: 'flutterexplore-cf65b',
    storageBucket: 'flutterexplore-cf65b.firebasestorage.app',
    iosBundleId: 'com.example.flutterexplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfKW8a3lzfKN4YrsMfSk3ZByj7Wt-cdD0',
    appId: '1:604492965652:ios:425af3da97b24031350401',
    messagingSenderId: '604492965652',
    projectId: 'flutterexplore-cf65b',
    storageBucket: 'flutterexplore-cf65b.firebasestorage.app',
    iosBundleId: 'com.example.flutterexplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD06RyvmpLi8YruM14woMgYU-5Hkj1VIdo',
    appId: '1:604492965652:web:dc26de0c39155d11350401',
    messagingSenderId: '604492965652',
    projectId: 'flutterexplore-cf65b',
    authDomain: 'flutterexplore-cf65b.firebaseapp.com',
    storageBucket: 'flutterexplore-cf65b.firebasestorage.app',
    measurementId: 'G-JMWJ6XX1EN',
  );

}